name: open-pr
on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
permissions:
  contents: write
  pull-requests: write
jobs:
  open:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          GH_TOKEN: ${{ github.token }}
          BRANCH: ${{ inputs.branch }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git switch -c "$BRANCH"
          echo "$BRANCH" > "$BRANCH.txt"
          git add . && git commit -m "add $BRANCH"
          git push origin "$BRANCH"
          gh pr create --title "$BRANCH" --body test --base main --head "$BRANCH"
